# Generated by Django 5.0 on 2023-12-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=50)),
                ('message', models.TextField(null=True)),
                ('calling_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
