# Generated by Django 5.0 on 2023-12-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skapp', '0009_rename_product_newproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('mrp', models.CharField(max_length=100)),
                ('gst', models.FloatField()),
                ('discription', models.TextField()),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('category', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
    ]
