# Generated by Django 5.0 on 2023-12-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skapp', '0010_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewProduct',
        ),
    ]
