# Generated by Django 5.0 on 2024-01-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skapp', '0012_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
