# Generated by Django 5.0 on 2024-01-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skapp', '0014_cartmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
