# Generated by Django 5.0 on 2024-01-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skapp', '0015_alter_cartmodel_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
