# Generated by Django 5.0 on 2024-01-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skapp', '0016_alter_cartmodel_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
