# Generated by Django 5.0 on 2024-01-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skapp', '0019_cartmodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='code',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
    ]
