# Generated by Django 5.0 on 2024-01-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skapp', '0020_alter_cartmodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
