# Generated by Django 5.0 on 2024-01-27 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skapp', '0021_alter_cartmodel_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skapp.product'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
