# Generated by Django 5.0 on 2024-01-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skapp', '0023_alter_cartmodel_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
