# Generated by Django 5.0 on 2024-01-30 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skapp', '0024_cartmodel_image_cartmodel_name_cartmodel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='code',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='status',
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skapp.product'),
        ),
    ]
