# Generated by Django 5.0 on 2024-01-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skapp', '0025_remove_cartmodel_code_remove_cartmodel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
