# Generated by Django 5.0 on 2024-02-08 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skapp', '0027_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_qty', models.IntegerField()),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skapp.order')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skapp.product')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
