# Generated by Django 5.0 on 2024-02-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skapp', '0029_country_state_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='trackingno',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
