# Generated by Django 5.0 on 2024-02-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skapp', '0030_alter_order_order_status_alter_order_trackingno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirm', 'Confirm'), ('deliver', 'Deliver'), ('cancel', 'Canceled'), ('return', 'Return'), ('refund', 'Refund')], default='pending', max_length=100),
        ),
    ]
