# Generated by Django 5.0 on 2024-02-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skapp', '0031_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='orderid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
