# Generated by Django 5.0 on 2024-02-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skapp', '0032_alter_orderitems_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderamt',
            field=models.FloatField(null=True),
        ),
    ]
