# Generated by Django 5.0 on 2024-02-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skapp', '0033_order_orderamt'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='orderdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
