# Generated by Django 5.0 on 2024-02-27 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skapp', '0034_orderitems_orderdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status_date', models.DateField(auto_now_add=True)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skapp.product')),
                ('trackingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skapp.orderitems')),
            ],
        ),
    ]
